version: "3"
services:
  mqtt_broker:
    image: eclipse-mosquitto:latest
    hostname: mqtt_broker
    volumes:
        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:z
        - ./passwd:/mosquitto/passwd:z
    ports:
      - 0.0.0.0:7707:7707
    restart: always
